service: titanic-prediction-api

provider:
  name: vercel

functions:
  predict:
    handler: main.app
    runtime: python3.9

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    layer: true

package:
  exclude:
    - node_modules/**
    - venv/**
    - __pycache__/**
    - data/**
